<?php


return array(
    'HTTP_STATUS_CODE_BAD_REQUEST'  => 400,
    'HTTP_STATUS_CODE_UNAUTHORIZED' => 401,
    'HTTP_STATUS_CODE_FORBIDDEN'    => 403,
    'HTTP_STATUS_CODE_NOT_FOUND'    => 404
);
